apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-app
  labels:
    app: netflix-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflix-app
  template:
    metadata:
      labels:
        app: netflix-app
    spec:
      containers:
      - name: netflix-app
        image: us-central1-docker.pkg.dev/seraphic-ripple-450910-m1/netflix-image/netflix:latest
        ports:
        - containerPort: 80
        env:
        - name: VITE_APP_TMDB_V3_API_KEY
          valueFrom:
            secretKeyRef:
              name: tmdb-api-secret
              key: TMDB_V3_API_KEY