name: Deploy to GKE

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PROJECT_ID: seraphic-ripple-450910-m1
  GKE_CLUSTER: netflix-host
  GKE_ZONE: us-central1-c

jobs:
  deploy:
    name: Deploy to GKE
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Authenticate with GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}  # Use the GitHub Secret

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.PROJECT_ID }}

    - name: Verify Authentication
      run: |
        gcloud auth list
        gcloud config list

    - name: Get GKE credentials
      uses: google-github-actions/get-gke-credentials@v2
      with:
        project_id: ${{ env.PROJECT_ID }}
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}

    - name: Create Secret for TMDB API Key
      run: |
        kubectl create secret generic tmdb-api-secret \
          --from-literal=TMDB_V3_API_KEY=${{ secrets.TMDB_API_KEY }} \
          --dry-run=client -o yaml | kubectl apply -f -

    - name: Deploy to GKE
      run: |
        kubectl apply -f kubernetes/deployment.yaml
        kubectl apply -f kubernetes/service.yaml
